name: Publish to gh-pages

on:
  push:
    branches:
      - main
  repository_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: main

      - name: setup node
        uses: actions/setup-node@v2
        with:
          node-version: 16.x
          cache: npm

      - name: install
        run: npm install

      - name: build
        run: npm run build

      # - name: preview
      #   run: npm run serve

      # - name: add nojekyll
      #   run: touch ./out/.nojekyll

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
